"""add document updated_at

Revision ID: 6141f6b1af91
Revises: 3ba9b3ae65e4
Create Date: 2026-07-23 13:54:24.022660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6141f6b1af91'
down_revision: Union[str, Sequence[str], None] = '3ba9b3ae65e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'documents',
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'updated_at')
    # ### end Alembic commands ###
