"""add chat document_id

Revision ID: 6c7fc571fed5
Revises: 1a5658bfeecb
Create Date: 2026-07-23 14:43:57.938435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c7fc571fed5'
down_revision: Union[str, Sequence[str], None] = '1a5658bfeecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('document_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chats', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'document_id')
    # ### end Alembic commands ###
